export const ROLES = {
  CUSTOMER: "CUSTOMER",
  VENDOR: "VENDOR",
  ADMIN: "ADMIN",
  SUPER_ADMIN: "SUPER_ADMIN",
};

export const VENDOR_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

export const SERVICE_STATUS = {
  DRAFT: "DRAFT",
  PUBLISHED: "PUBLISHED",
  SUSPENDED: "SUSPENDED",
};

export const BOOKING_STATUS = {
  PENDING: "PENDING",
  CONFIRMED: "CONFIRMED",
  COMPLETED: "COMPLETED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
};

export const PAYMENT_STATUS = {
  INITIATED: "INITIATED",
  SUCCESS: "SUCCESS",
  FAILED: "FAILED",
  REFUNDED: "REFUNDED",
};

export const PAYMENT_MODE = {
  PAY_NOW: "PAY_NOW",
  PAY_AFTER: "PAY_AFTER",
};

export const PAGE_SIZE = 10;